apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
      tier: auth-backend
  template:
    metadata:
      labels:
        app: auth-app
        tier: auth-backend
    spec:
      containers:
        - name: task-node
          image: deepchandr/multipod-k8-demo:authv6

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-app
    tier: auth-backend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8090
  type: ClusterIP
