apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
      tier: users-backend
  template:
    metadata:
      labels:
        app: users-app
        tier: users-backend
    spec:
      containers:
        - name: users-node
          image: deepchandr/multipod-k8-demo:usersv1

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-app
    tier: users-backend
  ports:
    - protocol: "TCP"
      port: 8085
      targetPort: 8085
  type: LoadBalancer
