apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
      tier: users-backend
  template:
    metadata:
      labels:
        app: users-app
        tier: users-backend
    spec:
      containers:
        - name: users-node
          image: deepchandr/multipod-k8-demo:userv5
          env:
            # - name: auth_host_url
            #   valueFrom:
            #     configMapKeyRef:
            #       name: data-store-env
            #       key: auth_host_url
            - name: auth_host_url
              value: "auth-service.default"

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-app
    tier: users-backend
  ports:
    - protocol: "TCP"
      port: 8085
      targetPort: 8085
  type: LoadBalancer
